### ISSUE TITLE
Server Keeps shutting down

### ISSUE THREAD

**Issue by maggotnap** [mtoensing/Docker-Minecraft-PaperMC-Server#116]
Hi, Server has worked for months, but just logged in and having issues now.
1. Just pulled the new image and rebuilt the container (1.21.3)
2. Have updated plugins that seem to be called out in the logs as errors or outdated.
3. Have also started removing newer plugins incase they are causing issues 
4. See docker compose.yml file 
[compose.txt](https://github.com/user-attachments/files/18056935/compose.txt)

The server starts fine, and runs through startup. When I join the world, the screen shows "Loading terrain..." and then sits for a minute or so, and then the server shuts down and restarts with a "Connection Lost, Timed out" Message, without anything being rendered on the screen.
When the screen does randomly render no '/' commands work 

Server log attached.
[_papermc_logs.txt](https://github.com/user-attachments/files/18056992/_papermc_logs.txt)

Looks like the server crashed a few days with errors for Worldguard, but I have removed that and this still happens.
[crash-2024-12-07_06.09.38-server.txt](https://github.com/user-attachments/files/18057110/crash-2024-12-07_06.09.38-server.txt)

Any thoughts?

**Comment by mtoensing** [comment]
The server crash on December 7, 2024, at 06:09:38, was caused by the WorldEdit plugin attempting to access its configuration before all platforms were fully registered. This led to a NoCapablePlatformException during the server’s initialization phase.

Error Details:

com.sk89q.worldedit.extension.platform.NoCapablePlatformException: Not all platforms have been registered yet! Please wait until WorldEdit is initialized.

This has nothing to do with the container. Please seek help at the paper community.

**Comment by maggotnap** [comment]
thanks
