### ISSUE TITLE
Raspberry pi problems

### ISSUE THREAD

**Issue by Dko1905** [mtoensing/Docker-Minecraft-PaperMC-Server#4]
When running it on a raspberry pi, I get the following error
```
standard_init_linux.go:207: exec user process caused "exec format error"
```
This is how I run it
```
sudo docker run --rm --name papermc -e MEMORYSIZE='500M' -p 25565:25565 -p 25575:25575 -i marctv/minecraft-papermc-server:latest
```
By the error description it sounds like an x86 program is trying to run on arm, which shouldn't be the case since it's Java.
If that's the case, can you add arm support?

**Comment by Dko1905** [comment]
I'm pretty sure that this causes the error:
```
# Install and run rcon
ARG RCON_CLI_VER=1.4.6
ADD https://github.com/itzg/rcon-cli/releases/download/${RCON_CLI_VER}/rcon-cli_${RCON_CLI_VER}_linux_amd64.tar.gz /tmp/rcon-cli.tgz
RUN tar -x -C /usr/local/bin -f /tmp/rcon-cli.tgz rcon-cli && \
  rm /tmp/rcon-cli.tgz
```

**Comment by mtoensing** [comment]
Please use this for the Raspberry Pi. Docker won't work: https://github.com/mtoensing/RaspberryPiMinecraft

**Comment by jhbruhn** [comment]
Why wouldn't work Docker in the long run? I want to try to run a Server on an RPi4 via Docker, why shouldn't it work, using a prober arm32v7 image of course?

**Comment by mtoensing** [comment]
Because Minecraft needs every bit of memory and performance. I am a huge fan of minecraft. I provide two successful docker images for Java https://github.com/mtoensing/Docker-Minecraft-PaperMC-Server and Bedrock https://github.com/mtoensing/Docker-Minecraft-Bedrock-Server
You can try and provide a link to a repository. But I think the overhead is not worth it. And I mean the overhead in maintenance and performance.
